@startuml

Title Singleton
left to right direction

class ThreadSafeSingleton{
+String context
-{static}ThreadSafeSingleton tsInstance
-ThreadSafeSingleton()
+{static}synchronized ThreadSafeSingleton getTSInstance()
+void log(String Thread)
}

class LazySingleton{
+String context
-{static}LazySingleton lazyInstance
-LazySingleton()
+{static}LazySingleton getLazyInstance()
+void log()
}

class Singleton_Main{
LazySingleton ls1
LazySingleton ls2
LazySingleton ls3
ThreadSafeSingleton ts1
ThreadSafeSingleton ts2
ThreadSafeSingleton ts3
boolean isLazy
}
class LazyThreading extends Thread{
+void run()
}
class TSThreading extends Thread{
+void run()
}




Singleton_Main ..> TSThreading : <<use>>
Singleton_Main ..> LazyThreading : <<use>>
Singleton_Main ..> ThreadSafeSingleton : <<use>>
Singleton_Main ..> LazySingleton : <<use>>

ThreadSafeSingleton --> ThreadSafeSingleton
LazySingleton --> LazySingleton

@enduml